### ISSUE TITLE
ERROR: cannot launch node of type [kfusion_ros/kfusion_node]: can't locate node [kfusion_node] in package [kfusion_ros]

### ISSUE THREAD

**Issue by dkanou** [tavu/kfusion_ros#1]
There is an error regarding the ROS node of the provided launch file.

**Comment by tavu** [comment]
Thank you for reporting this. It looks like that  the "catkin_package(CATKIN_DEPENDS)" directive was missing from CMakefile.txt. The lattest commit should fix this problem.
